#============ e2e-kind-config ====================
# iptables or ipvs, default iptables
E2E_KUBE_PROXY_MODE ?= iptables
# ipv4 or ipv6 or dual, default ipv4
E2E_IP_FAMILY ?= ipv4
# true is one node cluster, false is three node cluster, default true
E2E_SINGE_NODE ?= true
# kubernetes version, default v1.22.1
E2E_KIND_IMAGE_TAG ?= v1.22.1
# disable default cni, default true
E2E_DISABLE_DEFAULT_CNI ?= true

#============ ginkgo-custom-flag ====================
E2E_CLUSTER_NAME ?= spider
# multi flag separated by commas,like setup,ippool
E2E_GINKGO_LABELS ?= setup
