name: call e2e

env:
  CI_IMAGE_REPO: ghcr.io/spidernet-io/cni-plugins/meta-plugins
  PERFORMANCESCRIPT: "./tools/scripts/e2eperformance.sh"

on:
  workflow_call:
    inputs:
      ip_family:
        required: true
        type: string
      ref:
        required: false
        type: string
      push:
        required: false
        type: boolean

jobs:
  call_e2e:
    runs-on: ubuntu-latest
    outputs:
      result: ${{ steps.e2e.outputs.pass }}
      ref: ${{ steps.e2e.outputs.ref }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          persist-credentials: false
          ref: ${{ inputs.ref }}

      - name: Setup Golang
        uses: actions/setup-go@v3
        with:
          go-version: 1.19.0
          id: go

      - name: Install Ginkgo
        id: e2e
        run: |
          echo "pass=false" >> $GITHUB_OUTPUT
          exit 1
