name: call e2e kind init

env:
  CI_IMAGE_REPO: ghcr.io/spidernet-io/cni-plugins/meta-plugins

on:
  workflow_call:
    inputs:
      ip_family:
        required: true
        type: string
      ref:
        required: false
        type: string
      push:
        required: false
        type: boolean

jobs:
  call_e2e:
    runs-on: ubuntu-latest
    if: ${{ needs.get_ref.outputs.run_e2e == 'true' }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          persist-credentials: false
          ref: ${{ needs.get_ref.outputs.ref }}

      - name: Setup Golang
        uses: actions/setup-go@v3
        with:
          go-version: 1.19.0
          id: go

      - name: Install Ginkgo
        run:
          go install github.com/onsi/ginkgo/v2/ginkgo@v2.1.3
          ginkgo version

      # https://github.com/helm/kind-action
      - name: Install Kind Bin
        uses: helm/kind-action@v1.4.0
        with:
          install_only: true

      - name: Download ci image
        uses: actions/download-artifact@v3
        with:
          name: image-e2e-tar
          path: .tmp

      - name: Load Image to kind
        run: |
          TAR_FILES=` ls .tmp `
          echo $TAR_FILES
          for ITEM in ${TAR_FILES} ; do
              IMAGE_NAME=${ITEM%*.tar}
              cat .tmp/${ITEM} |  docker import - ghcr.io/${{ github.repository }}/meta-plugins:${{ needs.get_ref.outputs.tag }}
          done

      - name: Setup Kind Cluster For Dual-stack
        if: ${{ needs.get_ref.outputs.run_e2e == 'true' }}
        uses: nick-invision/retry@v2
        with:
          timeout_minutes: 10
          max_attempts: 3
          shell: bash
          command: |
            make -C test kind_init IP_FAMILY=${{ needs.get_ref.outputs.ip_family }} RUN_ON_LOCAL=false

      - name: Load ci image to kind
        if: ${{ needs.get_ref.outputs.run_e2e == 'true' }}
        uses: nick-invision/retry@v2
        with:
          timeout_minutes: 10
          max_attempts: 3
          shell: bash
          command: |
            kind load docker-image ghcr.io/${{ github.repository }}/meta-plugins:${{ needs.get_ref.outputs.tag }} --name dual

      - name: Install
        id: install
        if: ${{ needs.get_ref.outputs.run_e2e == 'true' }}
        continue-on-error: true
        run: |
          make -C test install IP_FAMILY=${{ needs.get_ref.outputs.ip_family }}  \
             META_PLUGINS_CI_TAG=ghcr.io/${{ github.repository }}/meta-plugins:${{ needs.get_ref.outputs.tag }}
             DEFAULT_CNI=k8s-pod-network

      - name: Setting vlan interface and create remote's client container
        if: ${{ needs.get_ref.outputs.run_e2e == 'true' }}
        id: vlan
        run:
          make -C test vlan IP_FAMILY=${{ needs.get_ref.outputs.ip_family }}

      - name: update apt-get sources_repo
        id: sources_repo
        run:
          make -C test update-repo

      - name: Run E2E For Dual-Stack
        id: dual
        if: ${{ needs.get_ref.outputs.run_e2e == 'true' }}
        continue-on-error: true
        run: |
            RESULT=0
            make -C test e2e IP_FAMILY=${{ needs.get_ref.outputs.ip_family }}
