name: test checkout

on:
  schedule:
    - cron: '* * * * *'

jobs:
  test-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: test check
      run: |
        echo "test check"
        git symbolic-ref --short HEAD
        ll /charts