name: test checkout

on:
  workflow_dispatch:
    inputs:
      ref:
        description: 'check chart test'
        required: true
        default: main

jobs:
  test-check:
    name: test-check11
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        if: ${{ github.event_name == 'workflow_dispatch' }}
        with:
          ref: ${{ github.event.inputs.tag }}

      - name: test check123
        run: |
          echo "test check"
          echo $(pwd)
          cd /home/runner/work/github-ci/github-ci
          echo $(ls)
          git symbolic-ref --short HEAD
          echo $(ll /charts)
