name: sync-chart-cron

on:
  workflow_dispatch:
    inputs:
      ref:
        description: 'check chart test'
        required: true
        default: main

jobs:
  sync-chart-cron-1:
    name: sync-chart-cron-2
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        if: ${{ github.event_name == 'workflow_dispatch' }}
        with:
          ref: ${{ github.event.inputs.tag }}

      - name: sync-chart-cron-3
        run: |
          echo -e ${GITHUB_WORKSPACE}
          bash ${GITHUB_WORKSPACE}/scripts/sync.sh
