name: Sync-Chart-Cronjob

on:
  workflow_dispatch:
    inputs:
      ref:
        description: 'check chart test'
        required: true
        default: main

jobs:
  Sync-Chart-Cronjob:
    name: sync-chart-cron
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        if: ${{ github.event_name == 'workflow_dispatch' }}
        with:
          ref: ${{ github.event.inputs.tag }}

      - name: Pull-and-Copy-Chart
        run: |
          bash ${GITHUB_WORKSPACE}/scripts/sync.sh

      - name: Auto-Pull-Request
        uses: repo-sync/pull-request@v2
        with:
          source_branch: ${BRANCH_NAME}
          destination_branch: "main"
          pr_title: "Automatic PR: Update multus helm chart(${TIME_NOW})"
          pr_label: "auto-pr"
          pr_assignee: "cyclinder"
          github_token: ${{ secrets.GITHUB_TOKEN }}


